# Generated by Django 2.1.7 on 2019-02-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='f_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.Grades'),
        ),
        migrations.AddField(
            model_name='comments',
            name='f_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interviews'),
        ),
        migrations.AddField(
            model_name='comments',
            name='f_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='f_grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.Grades'),
        ),
        migrations.AddField(
            model_name='answers',
            name='f_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Interviews'),
        ),
        migrations.AddField(
            model_name='answers',
            name='f_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions'),
        ),
    ]
