# Generated by Django 2.1.7 on 2019-03-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190227_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='f_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions'),
        ),
    ]
