# Generated by Django 2.1.7 on 2019-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20190312_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='weight',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
