# Generated by Django 2.1.7 on 2019-04-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_grades_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='active',
        ),
    ]
