# Generated by Django 2.1.7 on 2019-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_grades_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
