# Generated by Django 2.0.10 on 2019-09-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20190909_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
