# Generated by Django 3.0.6 on 2020-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_myself',
            field=models.TextField(),
        ),
    ]
