# Generated by Django 2.1.5 on 2019-08-14 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0002_auto_20190814_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 14, 19, 0, 18, 536868)),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
