# Generated by Django 2.1.5 on 2019-08-14 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0003_auto_20190814_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='epitome',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 14, 19, 10, 54, 476242)),
        ),
    ]
