# Generated by Django 2.1.5 on 2019-08-15 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0005_auto_20190815_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 15, 13, 5, 11, 768890))),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='epitome',
        ),
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeres', to='account_balance.Customer'),
        ),
    ]
