# Generated by Django 2.1.5 on 2019-08-15 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0006_auto_20190815_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 15, 20, 0, 39, 6981)),
        ),
    ]
