# Generated by Django 2.1.5 on 2019-08-19 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_balance', '0009_auto_20190819_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 19, 22, 44, 17, 75764))),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 19, 22, 44, 17, 74764)),
        ),
    ]
