# Generated by Django 2.1.7 on 2019-03-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190220_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='f_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Roles'),
        ),
    ]
