# Generated by Django 2.1.7 on 2019-03-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20190313_1542'),
        ('authorization', '0003_auto_20190306_0110'),
    ]

    operations = [
    ]
