# Generated by Django 2.1.7 on 2019-03-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', 'seed'),
        ('authorization', '0007_merge_20190314_1546'),
    ]

    operations = [
    ]
