# Generated by Django 2.1.7 on 2019-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_merge_20190314_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='avatar',
            field=models.URLField(default='https://s3.eu-west-2.amazonaws.com/techintbaseforavatar/default-avatar.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(default='null', max_length=60, unique=True),
        ),
    ]
