# Generated by Django 2.1.7 on 2019-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20190413_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.URLField(default='https://s3.eu-west-2.amazonaws.com/techintbaseforavatar/default-avatar.jpg', max_length=150),
        ),
    ]
