# Generated by Django 2.1.7 on 2019-04-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_auto_20190415_1121'),
        ('authorization', '0011_auto_20190415_2102'),
    ]

    operations = [
    ]
