# Generated by Django 2.1.7 on 2019-04-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_merge_20190415_1914'),
        ('authorization', '0010_auto_20190412_1534'),
    ]

    operations = [
    ]
