# Generated by Django 2.1.7 on 2019-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20190416_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.URLField(default='/static/images/avatar/default-avatar.jpg', max_length=150),
        ),
    ]
