# Generated by Django 2.1.7 on 2019-04-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20190416_1230'),
        ('authorization', '0013_merge_20190416_1448'),
    ]

    operations = [
    ]
