# Generated by Django 2.1.5 on 2019-01-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_like', models.BooleanField()),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='CourstitlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Courstitles',
            },
        ),
        migrations.CreateModel(
            name='ExpertusersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.AnswersModel')),
            ],
            options={
                'db_table': 'Expertusers',
            },
        ),
        migrations.CreateModel(
            name='GradesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='StepsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
                ('step_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='UserdataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Userdata',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.UserdataModel')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.RolesModel')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.StepsModel'),
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.CourstitlesModel'),
        ),
        migrations.AddField(
            model_name='expertusersmodel',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.GradesModel'),
        ),
        migrations.AddField(
            model_name='expertusersmodel',
            name='user_id_ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.UserdataModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.GradesModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.QuestionsModel'),
        ),
        migrations.AddField(
            model_name='answersmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.UsersModel'),
        ),
    ]
