# Generated by Django 2.1.5 on 2019-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsmodel',
            name='step_name',
            field=models.CharField(max_length=50),
        ),
    ]
