# Generated by Django 2.1.5 on 2019-01-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20190125_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsmodel',
            name='group_name',
        ),
    ]
