# Generated by Django 2.1.5 on 2019-01-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20190129_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsmodel',
            name='cours_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.CourstitlesModel'),
            preserve_default=False,
        ),
    ]
