# Generated by Django 2.1.5 on 2019-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_stepsmodel_cours_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='title_id',
            new_name='cours_id',
        ),
    ]
