# Generated by Django 2.1.5 on 2019-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20190129_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesmodel',
            name='grade_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
