# Generated by Django 2.1.5 on 2019-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_gradesmodel_grade_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
