# Generated by Django 3.0.6 on 2021-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyphrase',
            name='exist',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
