# Generated by Django 2.1.7 on 2019-02-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('interview_date', models.DateTimeField(default=None, null=True)),
                ('completion_date', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], default='scheduled', max_length=35)),
                ('f_candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_candidate_id', to=settings.AUTH_USER_MODEL)),
                ('f_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments')),
                ('f_expert', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_expert_id', to=settings.AUTH_USER_MODEL)),
                ('f_recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='f_recruiter_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['id'],
            },
        ),
    ]
