# Generated by Django 2.1.7 on 2019-03-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='f_candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_candidate_id', to='authorization.UserData'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='f_expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_expert_id', to='authorization.UserData'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='f_recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_recruiter_id', to='authorization.UserData'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='interview_date',
            field=models.DateTimeField(),
        ),
    ]
