# Generated by Django 2.1.7 on 2019-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20190326_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
