# Generated by Django 2.1.7 on 2019-04-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20190411_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewsRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_of_qualification', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('level', models.CharField(max_length=45)),
                ('level_com', models.TextField()),
                ('gaps', models.TextField()),
                ('gaps_com', models.TextField()),
                ('technical_english', models.CharField(max_length=45)),
                ('technical_english_com', models.TextField()),
                ('high_potential', models.CharField(max_length=45)),
                ('high_potential_com', models.TextField()),
                ('potentially_hire', models.CharField(max_length=45)),
                ('potentially_hire_com', models.TextField()),
                ('f_interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_interview_res', to='interviews.Interviews')),
            ],
            options={
                'db_table': 'interviewsRes',
                'ordering': ['id'],
            },
        ),
    ]
