# Generated by Django 2.1.7 on 2019-04-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interviewsres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsres',
            name='f_interview_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_interview_res_id', to='interviews.Interviews'),
        ),
    ]
