# Generated by Django 2.1.7 on 2019-04-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20190415_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsres',
            name='f_interview_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='f_interview_res_id', to='interviews.Interviews'),
        ),
    ]
