# Generated by Django 2.1.7 on 2019-02-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('hint', models.TextField(default=None, max_length=300, null=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['f_stage'],
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('f_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Sections')),
            ],
            options={
                'db_table': 'stages',
                'ordering': ['f_section'],
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='f_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Stages'),
        ),
    ]
